//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApiNetDemo.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int CourseId { get; set; }
        public int StudentId { get; set; }
        public System.DateTime CourseEnrollDate { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual AuthUser AuthUser { get; set; }
        public virtual AuthUser AuthUser1 { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
