//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApiNetDemo.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileNumber
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public bool IsPrimary { get; set; }
        public Nullable<int> UserProfile_Id { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
